### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aniketmaurya** [aniketmaurya/agents#2]
# Next up

- [x] Enable user provided tool
- [x] Integration with Cohere
- [ ] Integrate vLLM
- [ ] Create a pip package
- [ ] Create a LangChain custom LLM abstraction
